Added support for Spring Boot 3. (#32)
* Added support for Spring Boot 3.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -18,21 +18,26 @@ jobs:
       max-parallel: 100
       matrix:
         spring_boot_version:
-          - 2.6.5
-          - 2.5.11
-          - 2.4.13
+          - 3.0.6
+          - 2.7.11
+          - 2.6.14
     env:
       SPRING_BOOT_VERSION: ${{ matrix.spring_boot_version }}
       RUNS_IN_CI: "true"
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'zulu'
       - name: "Retrieve gradle settings"
-        uses: actions/cache@v2
+        uses: actions/cache@v3
         with:
           path: |
             ~/.gradle
-          key: gradle-v1-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', '**/*.gradle*') }}
+          key: gradle-v2-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', '**/*.gradle*') }}
       - name: "Assemble jar"
         run: GRADLE_USER_HOME=$HOME/.gradle ./gradlew assemble --console=plain --info --stacktrace
       - name: "Run tests"
@@ -40,7 +45,7 @@ jobs:
       - name: "Test if publishing works"
         run: GRADLE_USER_HOME=$HOME/.gradle ./gradlew publishToMavenLocal --console=plain --info --stacktrace
       - name: "Publish Test Report"
-        uses: mikepenz/action-junit-report@v2
+        uses: mikepenz/action-junit-report@v3
         if: always()
         with:
           report_paths: '**/build/test-results/**/*.xml'
@@ -56,9 +61,6 @@ jobs:
         uses: jwgmeligmeyling/spotbugs-github-action@master
         with:
           path: '**/build/reports/**/*.xml'
-      - name: "Tag release"
-        if: github.ref == 'refs/heads/master'
-        run: GRADLE_USER_HOME=$HOME/.gradle ./gradlew tagRelease --console=plain --info --stacktrace
 
   build:
     name: "Build and Test"
@@ -66,5 +68,24 @@ jobs:
       - ubuntu-latest
     needs: matrix_build
     steps:
-      - name: "Do something"
-        run: echo 'Matrix build was successful' 
+      # Needed hacks to properly fail the build when one matrix build fails.
+      - name: Do something so that GHA is happy
+        run: echo "Be happy!"
+      - name: Verify matrix jobs succeeded
+        if: ${{ needs.matrix_build.result != 'success' }}
+        run: exit 1
+      - name: "Install packages"
+        run: sudo apt-get update && sudo apt-get install -y git unzip
+      - name: Checkout repository
+        uses: actions/checkout@v3
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@v2
+        with:
+          gradle-home-cache-cleanup: true
+          # Comment out when you are upgrading gradle in a branch and doing tons of commits you would need to test.
+          # cache-read-only: false
+      - name: "Tag release"
+        if: github.ref == 'refs/heads/master'
+        uses: gradle/gradle-build-action@v2
+        with:
+          arguments: tagRelease --console=plain --info --stacktrace
